/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'points' : bigint,
  'avatar' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFixture' : ActorMethod<[string, string], boolean>,
  'addPost' : ActorMethod<[string, string], boolean>,
  'addPrediction' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkTickerTimer' : ActorMethod<[], boolean>,
  'createHub' : ActorMethod<[string, string], boolean>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllHubs' : ActorMethod<[], Array<[string, string]>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardData' : ActorMethod<
    [string],
    {
      'teamLogo' : [] | [ExternalBlob],
      'teamColor' : string,
      'fanPredictions' : Array<string>,
      'fixtures' : Array<string>,
      'communityPosts' : Array<[string, bigint]>,
      'newsFeed' : Array<string>,
      'playerImages' : Array<[string, ExternalBlob]>,
    }
  >,
  'getFeatureSectionData' : ActorMethod<
    [string],
    [] | [
      {
        'teamLogo' : [] | [ExternalBlob],
        'teamColor' : string,
        'fanPredictions' : Array<string>,
        'fixtures' : Array<string>,
        'communityPosts' : Array<[string, bigint]>,
        'newsFeed' : Array<string>,
        'playerImages' : Array<[string, ExternalBlob]>,
      }
    ]
  >,
  'getHub' : ActorMethod<[string], [] | [string]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getNewsTickerHeadlines' : ActorMethod<[], Array<string>>,
  'getNextFiveFixtures' : ActorMethod<[string], Array<string>>,
  'getPlayerRating' : ActorMethod<
    [string, bigint],
    { 'count' : bigint, 'average' : number }
  >,
  'getTopRatedPlayers' : ActorMethod<
    [string, bigint],
    Array<[bigint, number, bigint]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeTicker' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'migrateNewsTicker' : ActorMethod<[], undefined>,
  'ratePlayer' : ActorMethod<[string, bigint, bigint], boolean>,
  'refreshNewsTicker' : ActorMethod<[], Array<string>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTickerTimer' : ActorMethod<[], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateNews' : ActorMethod<[string, string], boolean>,
  'uploadPlayerImage' : ActorMethod<[string, string, ExternalBlob], boolean>,
  'uploadTeamLogo' : ActorMethod<[string, ExternalBlob], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];