/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'points' : IDL.Nat,
  'avatar' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFixture' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addPrediction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkTickerTimer' : IDL.Func([], [IDL.Bool], []),
  'createHub' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllHubs' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardData' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'teamLogo' : IDL.Opt(ExternalBlob),
          'teamColor' : IDL.Text,
          'fanPredictions' : IDL.Vec(IDL.Text),
          'fixtures' : IDL.Vec(IDL.Text),
          'communityPosts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
          'newsFeed' : IDL.Vec(IDL.Text),
          'playerImages' : IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
        }),
      ],
      [],
    ),
  'getFeatureSectionData' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'teamLogo' : IDL.Opt(ExternalBlob),
            'teamColor' : IDL.Text,
            'fanPredictions' : IDL.Vec(IDL.Text),
            'fixtures' : IDL.Vec(IDL.Text),
            'communityPosts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
            'newsFeed' : IDL.Vec(IDL.Text),
            'playerImages' : IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
          })
        ),
      ],
      ['query'],
    ),
  'getHub' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getNewsTickerHeadlines' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getNextFiveFixtures' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getPlayerRating' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Record({ 'count' : IDL.Nat, 'average' : IDL.Float64 })],
      ['query'],
    ),
  'getTopRatedPlayers' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeTicker' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'migrateNewsTicker' : IDL.Func([], [], []),
  'ratePlayer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'refreshNewsTicker' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTickerTimer' : IDL.Func([], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateNews' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'uploadPlayerImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Bool],
      [],
    ),
  'uploadTeamLogo' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'points' : IDL.Nat,
    'avatar' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFixture' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addPrediction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkTickerTimer' : IDL.Func([], [IDL.Bool], []),
    'createHub' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllHubs' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardData' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'teamLogo' : IDL.Opt(ExternalBlob),
            'teamColor' : IDL.Text,
            'fanPredictions' : IDL.Vec(IDL.Text),
            'fixtures' : IDL.Vec(IDL.Text),
            'communityPosts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
            'newsFeed' : IDL.Vec(IDL.Text),
            'playerImages' : IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
          }),
        ],
        [],
      ),
    'getFeatureSectionData' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'teamLogo' : IDL.Opt(ExternalBlob),
              'teamColor' : IDL.Text,
              'fanPredictions' : IDL.Vec(IDL.Text),
              'fixtures' : IDL.Vec(IDL.Text),
              'communityPosts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
              'newsFeed' : IDL.Vec(IDL.Text),
              'playerImages' : IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob)),
            })
          ),
        ],
        ['query'],
      ),
    'getHub' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getNewsTickerHeadlines' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getNextFiveFixtures' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPlayerRating' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Record({ 'count' : IDL.Nat, 'average' : IDL.Float64 })],
        ['query'],
      ),
    'getTopRatedPlayers' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeTicker' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'migrateNewsTicker' : IDL.Func([], [], []),
    'ratePlayer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'refreshNewsTicker' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTickerTimer' : IDL.Func([], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateNews' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'uploadPlayerImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Bool],
        [],
      ),
    'uploadTeamLogo' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };